import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/ui/app-sidebar";
import Script from "next/script";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <SidebarProvider>
                    <AppSidebar />
                    <main>
                        <SidebarTrigger />
                        {children}
                    </main>
                </SidebarProvider>
                <Script id="remove-grammarly-attrs">
                    {`
                    document.addEventListener('DOMContentLoaded', function() {
                        // Menghapus atribut Grammarly dari elemen HTML
                        const elementsWithGrammarly = document.querySelectorAll('[data-gr-ext-installed], [data-new-gr-c-s-check-loaded]');
                        elementsWithGrammarly.forEach(element => {
                            element.removeAttribute('data-gr-ext-installed');
                            element.removeAttribute('data-new-gr-c-s-check-loaded');
                        });
                    });
                    `}
                </Script>
            </body>
        </html>
    );
}
